hwi_oauth:
  firewall_names: ["main"]
  fosub:
         username_iterations: 30
         properties:
                 facebook: facebook_id
                 googleplus: googleplus_id
  resource_owners:
          facebook:
                  type: facebook
                  client_id: "%facebook_client_id%"
                  client_secret: "%facebook_secret%"
                  scope: "email"
                  infos_url: "https://graph.facebook.com/me?fields=email,name,id"

          google:
                  type: google
                  client_id: "%googleplus_client_id%"
                  client_secret: "%googleplus_secret%"
                  scope: "email profile"
