<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM4WHKbP\srcEnvDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM4WHKbP/srcEnvDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerM4WHKbP.legacy');

    return;
}

if (!\class_exists(srcEnvDebugProjectContainer::class, false)) {
    \class_alias(\ContainerM4WHKbP\srcEnvDebugProjectContainer::class, srcEnvDebugProjectContainer::class, false);
}

return new \ContainerM4WHKbP\srcEnvDebugProjectContainer([
    'container.build_hash' => 'M4WHKbP',
    'container.build_id' => '2c9a1348',
    'container.build_time' => 1736272642,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM4WHKbP');
