<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.8PYxaAd' shared service.

return $this->privates['.service_locator.8PYxaAd'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['uid' => function (): \App\Entity\User {
    return ($this->privates['.errored..service_locator.8PYxaAd.App\\Entity\\User'] ?? $this->load('getUser2Service.php'));
}]);
