<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fmNNzr1' shared service.

return $this->privates['.service_locator.fmNNzr1'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['id' => function (): \App\Entity\Content2 {
    return ($this->privates['.errored..service_locator.fmNNzr1.App\\Entity\\Content2'] ?? $this->load('getContent23Service.php'));
}]);
