<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.nPEjo_1' shared service.

return $this->privates['.service_locator.nPEjo_1'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['cid' => function (): \App\Entity\Comment {
    return ($this->privates['.errored..service_locator.nPEjo_1.App\\Entity\\Comment'] ?? $this->load('getCommentService.php'));
}, 'wid' => function (): \App\Entity\Wall {
    return ($this->privates['.errored..service_locator.nPEjo_1.App\\Entity\\Wall'] ?? $this->load('getWallService.php'));
}]);
