<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(['App\\Controller\\Friends2Controller::confirm' => function () {
    return ($this->privates['.service_locator.3UnAh_c'] ?? $this->load('get_ServiceLocator_3UnAhCService.php'));
}, 'App\\Controller\\FriendsController::confirm' => function () {
    return ($this->privates['.service_locator.3UnAh_c'] ?? $this->load('get_ServiceLocator_3UnAhCService.php'));
}, 'App\\Controller\\GroupAdminController::admindelete' => function () {
    return ($this->privates['.service_locator.fCcXuLg'] ?? $this->load('get_ServiceLocator_FCcXuLgService.php'));
}, 'App\\Controller\\GroupAdminController::delete' => function () {
    return ($this->privates['.service_locator.l_8OZkn'] ?? $this->load('get_ServiceLocator_L8OZknService.php'));
}, 'App\\Controller\\GroupAdminController::edit' => function () {
    return ($this->privates['.service_locator.l_8OZkn'] ?? $this->load('get_ServiceLocator_L8OZknService.php'));
}, 'App\\Controller\\GroupAdminController::show' => function () {
    return ($this->privates['.service_locator.l_8OZkn'] ?? $this->load('get_ServiceLocator_L8OZknService.php'));
}, 'App\\Controller\\GroupContent2Controller::delete' => function () {
    return ($this->privates['.service_locator.fmNNzr1'] ?? $this->load('get_ServiceLocator_FmNNzr1Service.php'));
}, 'App\\Controller\\GroupContent2Controller::edit' => function () {
    return ($this->privates['.service_locator.fmNNzr1'] ?? $this->load('get_ServiceLocator_FmNNzr1Service.php'));
}, 'App\\Controller\\GroupContent2Controller::index' => function () {
    return ($this->privates['.service_locator.Nksq2zn'] ?? $this->load('get_ServiceLocator_Nksq2znService.php'));
}, 'App\\Controller\\GroupContent2Controller::new' => function () {
    return ($this->privates['.service_locator.l_8OZkn'] ?? $this->load('get_ServiceLocator_L8OZknService.php'));
}, 'App\\Controller\\GroupContent2Controller::reply' => function () {
    return ($this->privates['.service_locator.ahWUdNc'] ?? $this->load('get_ServiceLocator_AhWUdNcService.php'));
}, 'App\\Controller\\GroupContentController::edit' => function () {
    return ($this->privates['.service_locator.BgnDCaz'] ?? $this->load('get_ServiceLocator_BgnDCazService.php'));
}, 'App\\Controller\\GroupContentController::new' => function () {
    return ($this->privates['.service_locator.l_8OZkn'] ?? $this->load('get_ServiceLocator_L8OZknService.php'));
}, 'App\\Controller\\GroupContentController::reply' => function () {
    return ($this->privates['.service_locator.FRP260j'] ?? $this->load('get_ServiceLocator_FRP260jService.php'));
}, 'App\\Controller\\GroupUserController::admindelete' => function () {
    return ($this->privates['.service_locator.fCcXuLg'] ?? $this->load('get_ServiceLocator_FCcXuLgService.php'));
}, 'App\\Controller\\GroupUserController::delete' => function () {
    return ($this->privates['.service_locator.l_8OZkn'] ?? $this->load('get_ServiceLocator_L8OZknService.php'));
}, 'App\\Controller\\GroupUserController::edit' => function () {
    return ($this->privates['.service_locator.l_8OZkn'] ?? $this->load('get_ServiceLocator_L8OZknService.php'));
}, 'App\\Controller\\GroupUserController::show' => function () {
    return ($this->privates['.service_locator.l_8OZkn'] ?? $this->load('get_ServiceLocator_L8OZknService.php'));
}, 'App\\Controller\\GroupUserController::subscribe' => function () {
    return ($this->privates['.service_locator.fCcXuLg'] ?? $this->load('get_ServiceLocator_FCcXuLgService.php'));
}, 'App\\Controller\\GroupUserController::unsubscribe' => function () {
    return ($this->privates['.service_locator.fCcXuLg'] ?? $this->load('get_ServiceLocator_FCcXuLgService.php'));
}, 'App\\Controller\\HelloWorldController::hello' => function () {
    return ($this->privates['.service_locator.Nksq2zn'] ?? $this->load('get_ServiceLocator_Nksq2znService.php'));
}, 'App\\Controller\\JQDemoController2::index' => function () {
    return ($this->privates['.service_locator.23tZE.l'] ?? $this->load('get_ServiceLocator_23tZE_LService.php'));
}, 'App\\Controller\\RootHelloController::index' => function () {
    return ($this->privates['.service_locator.Nksq2zn'] ?? $this->load('get_ServiceLocator_Nksq2znService.php'));
}, 'App\\Controller\\ShowDiscussController::index' => function () {
    return ($this->privates['.service_locator.Nksq2zn'] ?? $this->load('get_ServiceLocator_Nksq2znService.php'));
}, 'App\\Controller\\UserDeleteController::confirm' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserGalleryController::albummassdelete' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserGalleryController::comment' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserGalleryController::comment_edit' => function () {
    return ($this->privates['.service_locator.4FFQMPs'] ?? $this->load('get_ServiceLocator_4FFQMPsService.php'));
}, 'App\\Controller\\UserGalleryController::content' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserGalleryController::contentdelete' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserGalleryController::contentmassdelete' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserGalleryController::contentupload' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserGalleryController::gallerydelete' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserGalleryController::gallerytitleset' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserGalleryController::setavatar' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserPasswordController::index' => function () {
    return ($this->privates['.service_locator.tDAA6l6'] ?? $this->load('get_ServiceLocator_TDAA6l6Service.php'));
}, 'App\\Controller\\UserSettingsController::index' => function () {
    return ($this->privates['.service_locator.tDAA6l6'] ?? $this->load('get_ServiceLocator_TDAA6l6Service.php'));
}, 'App\\Controller\\UserSpaceController::add' => function () {
    return ($this->privates['.service_locator.DyJYoW9'] ?? $this->load('get_ServiceLocator_DyJYoW9Service.php'));
}, 'App\\Controller\\UserSpaceController::confirm' => function () {
    return ($this->privates['.service_locator.3UnAh_c'] ?? $this->load('get_ServiceLocator_3UnAhCService.php'));
}, 'App\\Controller\\UserSpaceController::fromuserspacegallery' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserSpaceController::fromuserspacegallerycomment' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserSpaceController::fromuserspacegallerycomment_edit' => function () {
    return ($this->privates['.service_locator.4FFQMPs'] ?? $this->load('get_ServiceLocator_4FFQMPsService.php'));
}, 'App\\Controller\\UserSpaceController::fromuserspacewall' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserSpaceController::index' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserSpaceController::userspacecomment_delete' => function () {
    return ($this->privates['.service_locator.nPEjo_1'] ?? $this->load('get_ServiceLocator_NPEjo1Service.php'));
}, 'App\\Controller\\UserSpaceController::userspacecomment_edit' => function () {
    return ($this->privates['.service_locator.nPEjo_1'] ?? $this->load('get_ServiceLocator_NPEjo1Service.php'));
}, 'App\\Controller\\UserSpaceController::userspacegallerycontent' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserSpaceController::userspacewall_comment' => function () {
    return ($this->privates['.service_locator.qHN584I'] ?? $this->load('get_ServiceLocator_QHN584IService.php'));
}, 'App\\Controller\\UserSpaceController::whits' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\WallController::comment' => function () {
    return ($this->privates['.service_locator.rNd6IAW'] ?? $this->load('get_ServiceLocator_RNd6IAWService.php'));
}, 'App\\Controller\\WallController::comment_delete' => function () {
    return ($this->privates['.service_locator.nPEjo_1'] ?? $this->load('get_ServiceLocator_NPEjo1Service.php'));
}, 'App\\Controller\\WallController::comment_edit' => function () {
    return ($this->privates['.service_locator.nPEjo_1'] ?? $this->load('get_ServiceLocator_NPEjo1Service.php'));
}, 'App\\Controller\\WallController::edit' => function () {
    return ($this->privates['.service_locator.rNd6IAW'] ?? $this->load('get_ServiceLocator_RNd6IAWService.php'));
}, 'App\\Controller\\WallController::post_delete' => function () {
    return ($this->privates['.service_locator.rNd6IAW'] ?? $this->load('get_ServiceLocator_RNd6IAWService.php'));
}, 'App\\Controller\\Friends2Controller:confirm' => function () {
    return ($this->privates['.service_locator.3UnAh_c'] ?? $this->load('get_ServiceLocator_3UnAhCService.php'));
}, 'App\\Controller\\FriendsController:confirm' => function () {
    return ($this->privates['.service_locator.3UnAh_c'] ?? $this->load('get_ServiceLocator_3UnAhCService.php'));
}, 'App\\Controller\\GroupAdminController:admindelete' => function () {
    return ($this->privates['.service_locator.fCcXuLg'] ?? $this->load('get_ServiceLocator_FCcXuLgService.php'));
}, 'App\\Controller\\GroupAdminController:delete' => function () {
    return ($this->privates['.service_locator.l_8OZkn'] ?? $this->load('get_ServiceLocator_L8OZknService.php'));
}, 'App\\Controller\\GroupAdminController:edit' => function () {
    return ($this->privates['.service_locator.l_8OZkn'] ?? $this->load('get_ServiceLocator_L8OZknService.php'));
}, 'App\\Controller\\GroupAdminController:show' => function () {
    return ($this->privates['.service_locator.l_8OZkn'] ?? $this->load('get_ServiceLocator_L8OZknService.php'));
}, 'App\\Controller\\GroupContent2Controller:delete' => function () {
    return ($this->privates['.service_locator.fmNNzr1'] ?? $this->load('get_ServiceLocator_FmNNzr1Service.php'));
}, 'App\\Controller\\GroupContent2Controller:edit' => function () {
    return ($this->privates['.service_locator.fmNNzr1'] ?? $this->load('get_ServiceLocator_FmNNzr1Service.php'));
}, 'App\\Controller\\GroupContent2Controller:index' => function () {
    return ($this->privates['.service_locator.Nksq2zn'] ?? $this->load('get_ServiceLocator_Nksq2znService.php'));
}, 'App\\Controller\\GroupContent2Controller:new' => function () {
    return ($this->privates['.service_locator.l_8OZkn'] ?? $this->load('get_ServiceLocator_L8OZknService.php'));
}, 'App\\Controller\\GroupContent2Controller:reply' => function () {
    return ($this->privates['.service_locator.ahWUdNc'] ?? $this->load('get_ServiceLocator_AhWUdNcService.php'));
}, 'App\\Controller\\GroupContentController:edit' => function () {
    return ($this->privates['.service_locator.BgnDCaz'] ?? $this->load('get_ServiceLocator_BgnDCazService.php'));
}, 'App\\Controller\\GroupContentController:new' => function () {
    return ($this->privates['.service_locator.l_8OZkn'] ?? $this->load('get_ServiceLocator_L8OZknService.php'));
}, 'App\\Controller\\GroupContentController:reply' => function () {
    return ($this->privates['.service_locator.FRP260j'] ?? $this->load('get_ServiceLocator_FRP260jService.php'));
}, 'App\\Controller\\GroupUserController:admindelete' => function () {
    return ($this->privates['.service_locator.fCcXuLg'] ?? $this->load('get_ServiceLocator_FCcXuLgService.php'));
}, 'App\\Controller\\GroupUserController:delete' => function () {
    return ($this->privates['.service_locator.l_8OZkn'] ?? $this->load('get_ServiceLocator_L8OZknService.php'));
}, 'App\\Controller\\GroupUserController:edit' => function () {
    return ($this->privates['.service_locator.l_8OZkn'] ?? $this->load('get_ServiceLocator_L8OZknService.php'));
}, 'App\\Controller\\GroupUserController:show' => function () {
    return ($this->privates['.service_locator.l_8OZkn'] ?? $this->load('get_ServiceLocator_L8OZknService.php'));
}, 'App\\Controller\\GroupUserController:subscribe' => function () {
    return ($this->privates['.service_locator.fCcXuLg'] ?? $this->load('get_ServiceLocator_FCcXuLgService.php'));
}, 'App\\Controller\\GroupUserController:unsubscribe' => function () {
    return ($this->privates['.service_locator.fCcXuLg'] ?? $this->load('get_ServiceLocator_FCcXuLgService.php'));
}, 'App\\Controller\\HelloWorldController:hello' => function () {
    return ($this->privates['.service_locator.Nksq2zn'] ?? $this->load('get_ServiceLocator_Nksq2znService.php'));
}, 'App\\Controller\\JQDemoController2:index' => function () {
    return ($this->privates['.service_locator.23tZE.l'] ?? $this->load('get_ServiceLocator_23tZE_LService.php'));
}, 'App\\Controller\\RootHelloController:index' => function () {
    return ($this->privates['.service_locator.Nksq2zn'] ?? $this->load('get_ServiceLocator_Nksq2znService.php'));
}, 'App\\Controller\\ShowDiscussController:index' => function () {
    return ($this->privates['.service_locator.Nksq2zn'] ?? $this->load('get_ServiceLocator_Nksq2znService.php'));
}, 'App\\Controller\\UserDeleteController:confirm' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserGalleryController:albummassdelete' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserGalleryController:comment' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserGalleryController:comment_edit' => function () {
    return ($this->privates['.service_locator.4FFQMPs'] ?? $this->load('get_ServiceLocator_4FFQMPsService.php'));
}, 'App\\Controller\\UserGalleryController:content' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserGalleryController:contentdelete' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserGalleryController:contentmassdelete' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserGalleryController:contentupload' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserGalleryController:gallerydelete' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserGalleryController:gallerytitleset' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserGalleryController:setavatar' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserPasswordController:index' => function () {
    return ($this->privates['.service_locator.tDAA6l6'] ?? $this->load('get_ServiceLocator_TDAA6l6Service.php'));
}, 'App\\Controller\\UserSettingsController:index' => function () {
    return ($this->privates['.service_locator.tDAA6l6'] ?? $this->load('get_ServiceLocator_TDAA6l6Service.php'));
}, 'App\\Controller\\UserSpaceController:add' => function () {
    return ($this->privates['.service_locator.DyJYoW9'] ?? $this->load('get_ServiceLocator_DyJYoW9Service.php'));
}, 'App\\Controller\\UserSpaceController:confirm' => function () {
    return ($this->privates['.service_locator.3UnAh_c'] ?? $this->load('get_ServiceLocator_3UnAhCService.php'));
}, 'App\\Controller\\UserSpaceController:fromuserspacegallery' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserSpaceController:fromuserspacegallerycomment' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserSpaceController:fromuserspacegallerycomment_edit' => function () {
    return ($this->privates['.service_locator.4FFQMPs'] ?? $this->load('get_ServiceLocator_4FFQMPsService.php'));
}, 'App\\Controller\\UserSpaceController:fromuserspacewall' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserSpaceController:index' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserSpaceController:userspacecomment_delete' => function () {
    return ($this->privates['.service_locator.nPEjo_1'] ?? $this->load('get_ServiceLocator_NPEjo1Service.php'));
}, 'App\\Controller\\UserSpaceController:userspacecomment_edit' => function () {
    return ($this->privates['.service_locator.nPEjo_1'] ?? $this->load('get_ServiceLocator_NPEjo1Service.php'));
}, 'App\\Controller\\UserSpaceController:userspacegallerycontent' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\UserSpaceController:userspacewall_comment' => function () {
    return ($this->privates['.service_locator.qHN584I'] ?? $this->load('get_ServiceLocator_QHN584IService.php'));
}, 'App\\Controller\\UserSpaceController:whits' => function () {
    return ($this->privates['.service_locator.8PYxaAd'] ?? $this->load('get_ServiceLocator_8PYxaAdService.php'));
}, 'App\\Controller\\WallController:comment' => function () {
    return ($this->privates['.service_locator.rNd6IAW'] ?? $this->load('get_ServiceLocator_RNd6IAWService.php'));
}, 'App\\Controller\\WallController:comment_delete' => function () {
    return ($this->privates['.service_locator.nPEjo_1'] ?? $this->load('get_ServiceLocator_NPEjo1Service.php'));
}, 'App\\Controller\\WallController:comment_edit' => function () {
    return ($this->privates['.service_locator.nPEjo_1'] ?? $this->load('get_ServiceLocator_NPEjo1Service.php'));
}, 'App\\Controller\\WallController:edit' => function () {
    return ($this->privates['.service_locator.rNd6IAW'] ?? $this->load('get_ServiceLocator_RNd6IAWService.php'));
}, 'App\\Controller\\WallController:post_delete' => function () {
    return ($this->privates['.service_locator.rNd6IAW'] ?? $this->load('get_ServiceLocator_RNd6IAWService.php'));
}]));
