<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\UserBundle\EventListener\AvatarAddRegister' shared autowired service.

include_once $this->targetDirs[3].'/src/UserBundle/EventListener/AvatarAddRegister.php';

return $this->privates['App\\UserBundle\\EventListener\\AvatarAddRegister'] = new \App\UserBundle\EventListener\AvatarAddRegister(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')));
