<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'hwi_oauth.http_client' shared service.

include_once $this->targetDirs[3].'/vendor/php-http/httplug/src/HttpClient.php';
include_once $this->targetDirs[3].'/vendor/php-http/client-common/src/HttpMethodsClient.php';

return $this->services['hwi_oauth.http_client'] = new \Http\Client\Common\HttpMethodsClient(($this->services['hwi_oauth.http.client'] ?? $this->load('getHwiOauth_Http_ClientService.php')), ($this->services['hwi_oauth.http.message_factory'] ?? $this->load('getHwiOauth_Http_MessageFactoryService.php')));
