<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVuId6oi\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVuId6oi/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerVuId6oi.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerVuId6oi\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerVuId6oi\srcProdProjectContainer([
    'container.build_hash' => 'VuId6oi',
    'container.build_id' => '0a9e8a7f',
    'container.build_time' => 1736272624,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVuId6oi');
