<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.4FFQMPs' shared service.

return $this->privates['.service_locator.4FFQMPs'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['gcid' => function (): \App\Entity\GalleryComment {
    return ($this->privates['.errored..service_locator.4FFQMPs.App\\Entity\\GalleryComment'] ?? $this->load('getGalleryCommentService.php'));
}]);
