<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ahWUdNc' shared service.

return $this->privates['.service_locator.ahWUdNc'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['cid' => function (): \App\Entity\Content2 {
    return ($this->privates['.errored..service_locator.ahWUdNc.App\\Entity\\Content2'] ?? $this->load('getContent22Service.php'));
}, 'gid' => function (): \App\Entity\Group {
    return ($this->privates['.errored..service_locator.ahWUdNc.App\\Entity\\Group'] ?? $this->load('getGroup3Service.php'));
}]);
