<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fCcXuLg' shared service.

return $this->privates['.service_locator.fCcXuLg'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['groupid' => function (): \App\Entity\Group {
    return ($this->privates['.errored..service_locator.fCcXuLg.App\\Entity\\Group'] ?? $this->load('getGroup4Service.php'));
}]);
