<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.DyJYoW9' shared service.

return $this->privates['.service_locator.DyJYoW9'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['pid' => function (): \App\Entity\User {
    return ($this->privates['.errored..service_locator.DyJYoW9.App\\Entity\\User'] ?? $this->load('getUser3Service.php'));
}, 'uid' => function (): \App\Entity\User {
    return ($this->privates['.errored..service_locator.DyJYoW9.App\\Entity\\User'] ?? $this->load('getUser3Service.php'));
}]);
