<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.4FFQMPs.App\Entity\GalleryComment' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.4FFQMPs": it references class "App\\Entity\\GalleryComment" but no such service exists.');
