<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'hwi_oauth.resource_owner.google' shared service.

include_once $this->targetDirs[3].'/vendor/hwi/oauth-bundle/OAuth/ResourceOwnerInterface.php';
include_once $this->targetDirs[3].'/vendor/hwi/oauth-bundle/OAuth/ResourceOwner/AbstractResourceOwner.php';
include_once $this->targetDirs[3].'/vendor/hwi/oauth-bundle/OAuth/ResourceOwner/GenericOAuth2ResourceOwner.php';
include_once $this->targetDirs[3].'/vendor/hwi/oauth-bundle/OAuth/ResourceOwner/GoogleResourceOwner.php';

return $this->services['hwi_oauth.resource_owner.google'] = new \HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\GoogleResourceOwner(($this->services['hwi_oauth.http_client'] ?? $this->load('getHwiOauth_HttpClientService.php')), ($this->privates['security.http_utils'] ?? $this->getSecurity_HttpUtilsService()), ['client_id' => '428367507179-7nsf5k9hedmnr22bqdlon246tvjbtphn', 'client_secret' => 'AotzVV60Pxv59b4xRtp3Tr-P', 'scope' => 'email profile', 'paths' => [], 'options' => []], 'google', ($this->privates['hwi_oauth.storage.session'] ?? $this->load('getHwiOauth_Storage_SessionService.php')));
