<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.l_8OZkn' shared service.

return $this->privates['.service_locator.l_8OZkn'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['id' => function (): \App\Entity\Group {
    return ($this->privates['.errored..service_locator.l_8OZkn.App\\Entity\\Group'] ?? $this->load('getGroup5Service.php'));
}]);
