<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.tDAA6l6' shared service.

return $this->privates['.service_locator.tDAA6l6'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['encoderFactory' => function () {
    return ($this->privates['security.encoder_factory.generic'] ?? $this->load('getSecurity_EncoderFactory_GenericService.php'));
}, 'tokenStorage' => function () {
    return ($this->services['security.token_storage'] ?? ($this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage()));
}]);
