<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.FRP260j' shared service.

return $this->privates['.service_locator.FRP260j'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['cid' => function (): \App\Entity\Content {
    return ($this->privates['.errored..service_locator.FRP260j.App\\Entity\\Content'] ?? $this->load('getContent2Service.php'));
}, 'gid' => function (): \App\Entity\Group {
    return ($this->privates['.errored..service_locator.FRP260j.App\\Entity\\Group'] ?? $this->load('getGroup2Service.php'));
}]);
