<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.23tZE.l' shared service.

return $this->privates['.service_locator.23tZE.l'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['gid' => function (): \App\Entity\Group {
    return ($this->privates['.errored..service_locator.23tZE.l.App\\Entity\\Group'] ?? $this->load('getGroupService.php'));
}]);
