<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hwi_oauth.storage.session' shared service.

include_once $this->targetDirs[3].'/vendor/hwi/oauth-bundle/OAuth/RequestDataStorageInterface.php';
include_once $this->targetDirs[3].'/vendor/hwi/oauth-bundle/OAuth/RequestDataStorage/SessionStorage.php';

return $this->privates['hwi_oauth.storage.session'] = new \HWI\Bundle\OAuthBundle\OAuth\RequestDataStorage\SessionStorage(($this->services['session'] ?? $this->getSessionService()));
