<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'hwi_oauth.resource_owner.facebook' shared service.

include_once $this->targetDirs[3].'/vendor/hwi/oauth-bundle/OAuth/ResourceOwnerInterface.php';
include_once $this->targetDirs[3].'/vendor/hwi/oauth-bundle/OAuth/ResourceOwner/AbstractResourceOwner.php';
include_once $this->targetDirs[3].'/vendor/hwi/oauth-bundle/OAuth/ResourceOwner/GenericOAuth2ResourceOwner.php';
include_once $this->targetDirs[3].'/vendor/hwi/oauth-bundle/OAuth/ResourceOwner/FacebookResourceOwner.php';

return $this->services['hwi_oauth.resource_owner.facebook'] = new \HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\FacebookResourceOwner(($this->services['hwi_oauth.http_client'] ?? $this->load('getHwiOauth_HttpClientService.php')), ($this->privates['security.http_utils'] ?? $this->getSecurity_HttpUtilsService()), ['client_id' => '2410465105923571', 'client_secret' => '25cef29759c22c1fe5ad0b8bbbc30e7c', 'scope' => 'email', 'infos_url' => 'https://graph.facebook.com/me?fields=email,name,id', 'paths' => [], 'options' => []], 'facebook', ($this->privates['hwi_oauth.storage.session'] ?? $this->load('getHwiOauth_Storage_SessionService.php')));
