<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.qHN584I' shared service.

return $this->privates['.service_locator.qHN584I'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['uid' => function (): \App\Entity\Wall {
    return ($this->privates['.errored..service_locator.qHN584I.App\\Entity\\Wall'] ?? $this->load('getWall2Service.php'));
}]);
