<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.BgnDCaz' shared service.

return $this->privates['.service_locator.BgnDCaz'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['id' => function (): \App\Entity\Content {
    return ($this->privates['.errored..service_locator.BgnDCaz.App\\Entity\\Content'] ?? $this->load('getContentService.php'));
}]);
