<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.rNd6IAW' shared service.

return $this->privates['.service_locator.rNd6IAW'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['id' => function (): \App\Entity\Wall {
    return ($this->privates['.errored..service_locator.rNd6IAW.App\\Entity\\Wall'] ?? $this->load('getWall3Service.php'));
}]);
