<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.ahWUdNc.App\Entity\Content2' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.ahWUdNc": it references class "App\\Entity\\Content2" but no such service exists.');
