<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.FRP260j.App\Entity\Group' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.FRP260j": it references class "App\\Entity\\Group" but no such service exists.');
