<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\RegistrationController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/Controller.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/user-bundle/Controller/RegistrationController.php';
include_once $this->targetDirs[3].'/src/Controller/RegistrationController.php';

$this->services['App\\Controller\\RegistrationController'] = $instance = new \App\Controller\RegistrationController(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->privates['fos_user.registration.form.factory'] ?? $this->load('getFosUser_Registration_Form_FactoryService.php')), ($this->services['fos_user.user_manager'] ?? $this->load('getFosUser_UserManagerService.php')), ($this->services['security.token_storage'] ?? ($this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage())));

$instance->setContainer($this);

return $instance;
