<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQdvAxTU\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQdvAxTU/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQdvAxTU.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQdvAxTU\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQdvAxTU\srcDevDebugProjectContainer([
    'container.build_hash' => 'QdvAxTU',
    'container.build_id' => '11f8be2a',
    'container.build_time' => 1736272657,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQdvAxTU');
